### ISSUE TITLE
!!!!!!!! Model.php | $var[] = new $obj($data); | getAll & getOne.

### ISSUE THREAD

**Issue by Juju075** [Juju075/Openclassrooms#27]
Fatal error: Uncaught Error: Class 'Article' not found in C:\wamp64\www\App_Blog_MVC\framework\Model.php on line 66
***************
`new $obj($data)`
$obj c l'entité cible ( Article, Comment ou User)
***************
probleme de path.

**Comment by Juju075** [comment]
Non c pas un probleme de path
Il trouve pas la class.

**Comment by itahriouan1** [comment]
Il ne trouve pas l'objet car l'objet appartient à un namespace
il faut alors ajouter le namespace:
$obj2="\\Entity\\".$obj;
$var[] = new $obj2($data);

**Comment by itahriouan1** [comment]
les attributs id et chapo ne s'affiche pas en raison de l'absence des setters ou du nom de setter incohérent dans la classe Article:
donc dans article.php il faut ajouter:
    public function setChapo(?string $chapo) 
    {
        if(is_string($chapo)){
            $this->_chapo = $chapo;
        }
    }

il faut aussi corriger le nom du setter setId par setId_article

**Comment by Juju075** [comment]
ok syntax corrige \\
