### ISSUE TITLE
Methods inside Model.php shouldn't be specific to any entity 

### ISSUE THREAD

**Issue by itahriouan1** [Juju075/Openclassrooms#38]
for example createOne should persist any obrject in database. to do so, inside ArticleController we have to create an object from $_POST :
`$article= new Article($_POST);`
then we have to send $article object as a parameter in createArticle methode:
`$article = $this->_articleManager->createArticle($article);`
this is how store fuction should become:
```
private function store(){
        if (isset($_POST)){
            $article= new Article($_POST);
            $this->_articleManager = new ArticleManager;
            $article = $this->_articleManager->createArticle($article);
            $articles = $this->_articleManager->getArticles();
            $this->_view = new View('Accueil','Post');
            $this->_view->generate(array('articles' =>$articles));
        }
    }
```
as we send $article abject as a parameter in createArticle methode, we should modify it in ArticleManager to support this modification:
```
   public function createArticle($article){
      return $this->CreateOne('article',$article);
   } 
```
finally, in createOne Methode in Model.php we have to capture the object sent using CreateOne methode and we should persist it in the coresponding table (methode shouldn't be specific to object and should be valuable to any entity object):
```
protected function createOne($table, $obj){
        $array=(array)$obj;
        $classFullName=get_class($obj);
        var_dump($array);
        var_dump($classFullName);
        $keys=[];
        $values=[];
        $data=[];
        $interrogation=[];
        foreach ($array as $key=>$value){
            
            array_push($keys, strtolower(substr(str_replace($classFullName,"",$key),3)));
            array_push($values, $value);
            array_push($interrogation,'?');
            $data[strtolower($key)]=$value;
        }
        var_dump($keys);
        $keysString=implode(' , ',$keys);
        $interrogationString=implode(' , ',$interrogation);
        $this->getBdd();
        $sql="INSERT INTO ".$table." (".$keysString.") VALUES (".$interrogationString.")";
        echo $sql;
        try {$req = self::$_bdd->prepare($sql);
            $req->execute($values);}
            catch(\PDOException $e)
            {
                $e->errorInfo;
            }
        
        $req->closeCursor();
    }

```

**Comment by Juju075** [comment]
Bonsoir ok je regarde ça.

Le lun. 27 sept. 2021 à 22:14, itahriouan1 ***@***.***> a
écrit :

**Comment by Juju075** [comment]
Model.php getBdd 
(".$keysString.")
`INSERT INTO user (rname , sword , il , ivated , idation_key , rtype , nom , , tar) VALUES (? , ? , ? , ? , ? , ? , ? , ? , ?)`

**Les clés récupéré sont pas correct.** 

C:\wamp64\www\App_Blog_MVC\framework\Model.php:213:string 
'rname , sword , il , ivated , idation_key , rtype , nom ,  , tar' (length=64)

**Comment by itahriouan1** [comment]
le problème vient du fait que dans Article.php les attributs commencent par un underscore (par exemple $_title, $_chapo) alors que dans user y a pas d'underscore (par exemple: $username, $password ...) comme ça dans Model.php on supprimme l'underscore dans la ligne : array_push($keys, strtolower(substr(str_replace($classFullName,"",$key),3))); c'est la fonction substr qui fait ça. la solution donc consiste à ajouter des underscores dans les attributs de User et toutes les entités qui restent, ou bien supprimer l'underscore dans toutes les attributs des classes entités et remplcer 3 dans substr par 1.

**Comment by Juju075** [comment]
ok j'avais hésité je sais pas pourquoi il met _.

**Comment by Juju075** [comment]
oui
**(  _  ) en préfix d'attribut c pas conseillé?**

Je vois il supprime (  _  ) dans construct() 
`$key = lcfirst(str_replace('_', '', ucwords($key, '_')));`

Bon c pas grave on fini ça et on passe à Symfony.

**Comment by itahriouan1** [comment]
la première erreur c'etait en raison de la non création de l'objet User dans le controller dans la méthode store(). il faut créer un objet user en passant $array : $user= new User($array); 
la méthode store doit se définir comme suit:
```
private function store(){
        echo('ControllerRegister store2');

        if (isset($_POST)){
        ;

            $pass_hache = password_hash($_POST['password'], PASSWORD_DEFAULT);
            $token = '123456'; //random_bytes (10); // a corriger
            $default_avatar = 'default_avatar.jpg';

            $array = array('username'=> $_POST['username'],'password'=> $pass_hache,'email'=> $_POST['email'],'activated'=>'1','validation_key'=> $token,'usertype'=>'1','prenom'=> $_POST['prenom'],'nom'=> $_POST['nom'],'avatar' => $default_avatar);
            $user= new User($array);
            $userManager= new UserManager();
            var_dump($user);
            $userManager->add2($user);
        }
```
remarque: il faut trouver un autre nom pour la méthode add2 
la majorité des problèmes vient de l'absence ou la non adéquation des méthodes dans User avec les noms des champs dans la BD : 
1- fermer accolade de la méthode setPrenom
2- définir setActivated:
```
public function setActivated(int $Activated)
    {
        $this->activated= $Activated;
    }
```
3- meme chose pour usertype:
```
public function setUsertype(int $usertype){
        $this->usertype=$usertype;

    }
```
4- modifier private $userType; par private $usertype; ça rend plus simple même si ça respect pas la convention de nommage.
5- définir getUsertype:
```
public function getUsertype(){
        return $this->usertype;
    }
```

**Comment by Juju075** [comment]
tester
