### ISSUE TITLE
Bloqué - 90% S'inscrire || Codeguy/Upload || N'enregistre pas l'image. Directory? (No image choice)  Pas clair Pb empty  !isset() != null ?

### ISSUE THREAD

**Issue by Juju075** [Juju075/Openclassrooms#41]

**Comment by Juju075** [comment]
Besoin framework gere les uploads php.

**Comment by Juju075** [comment]
frameork installe codeguy/upload pour PHP

Traitement manque un use 
`new \Upload`

**Comment by Juju075** [comment]
Ne charge pas les dependences.

Il trouve bien
`$storage = new \Upload\Storage\FileSystem('/public/images/upload');`

Mais pas
```
new \Upload\File
ew \Upload\Validation\
```

**Comment by Juju075** [comment]
Probleme disparu !!!

**Comment by Juju075** [comment]
ok

Faire le traitment de l'image en premier pour pouvoir recuperer le nom du fichier telecharger.
condition upload optionnel si non telecharger mettre fichier image par défault.

OK

**Comment by Juju075** [comment]
Aucun resultat de storage et file ????

```
        $storage = new \Upload\Storage\FileSystem('/public/images/upload');  //dans vendor
        echo('jusqu\'ici tout vas bien');
        $file = new \Upload\File('foo', $storage); //validation et enregistrement du fichier.
```

**Comment by Juju075** [comment]
ok je regarde

**Comment by Juju075** [comment]
**ControllerRegister imageUpload**

array (size=0)
  empty

**Comment by Juju075** [comment]
Stackoverflow say:

I have WampServer 2 installed on my Windows 7 computer. I'm using Apache 2.2.11 and PHP 5.2.11. When I attempt to upload any file from a form, it seems to upload, but in PHP, the $_FILES array is empty. There is no file in the c:\wamp\tmp folder. I have configured php.ini to allow file uploads and such. The tmp folder has read/write privileges for the current user. I'm stumped.

**Comment by itahriouan1** [comment]
yes but I see that this copy/paste is not well done because we can't define a form inside another! that's my first remark. so as expected, the file register.html.twig is not well defined

**Comment by Juju075** [comment]
ha si javais vu mais comment faire pour
`enctype="multipart/form-data"`

on peut le mettre dans le premier method post ?

**Comment by itahriouan1** [comment]
I will try to correct the file code

**Comment by Juju075** [comment]
ok je fini twig. Merci

**Comment by itahriouan1** [comment]
whe should have one form that send all content. for enctype="multipart/form-data" proprety, yes! that's what we should do! one form and add this proprety in the form

**Comment by Juju075** [comment]
ok

**Comment by Juju075** [comment]
ok thx

**Comment by Juju075** [comment]
TESTS
*********************************************
Sauf erreur implentation html form / function store / codejuy code.

Erreur:
Notice: Undefined index: foo 

Test 1 - Formulaire ( mettre séparement l'ajout de l'image).

**Comment by Juju075** [comment]
Tesst 
formulaire sans image.
erreur  Undefined index: foo (c normal pas choisi de fichier).
par contre php affiche une erreur

enlevé var_dump
ok résolu.
***********************************
formulaire avec image
