### ISSUE TITLE
83% - SymfonyInsight - Bindparam()

### ISSUE THREAD

**Issue by Juju075** [Juju075/Openclassrooms#64]
Your project database queries must use safety features such as bindings
******************************************
use parameter binding.

**Comment by itahriouan1** [comment]
as there is no way to bind table name in pdo, the only way to pass table name in sql reqest is to use variables in sql request. symfony Insight mention that as critical to avoid passing sql injection attacks. to validate code in symfony insight there is multiple ways based on 3rd party librarys or orm like doctrine. As it is not recomended in the project requirements in openclassrooms, the only solution is to use switch for table name variable and write sql request for evry table. for example:

```
    protected function getAll($table, $obj){
        $this->getBdd();
        $var = [];
        $id='id_'.$table;
        switch($table)
        {
            case 'article':
                $sql = 'SELECT * FROM article ORDER BY :id desc';
                break;
            case 'comment':
                $sql = 'SELECT * FROM comment ORDER BY :id desc';
                break;
        }
        $req  = self::$_bdd->prepare($sql);  //binparam
        $req->bindValue(':id', $id);
        $req->execute();

        while ($data = $req->fetch(\PDO::FETCH_ASSOC)){
            $obj2="\\Entity\\".$obj;
            $var[] = new $obj2($data);
        }
        return $var;
        $req->closeCursor();
    }
```
this is not the perfect way but it avoids direct injection in sql request wich make it accepted in symfony Insight

**Comment by Juju075** [comment]
ok i look at this.. thanks

**Comment by Juju075** [comment]
Ok nice trick.
you skip using directly the $table in SQL.
