### ISSUE TITLE
Image upload !!! Setup avatar on profile page and comments'cards

### ISSUE THREAD

**Issue by Juju075** [Juju075/Openclassrooms#74]

**Comment by itahriouan1** [comment]
I have resolved the problem
first, i change directory to:
$storage = new \Upload\Storage\FileSystem( __DIR__."/../uploads/images/");
I created a folder /uploads/images/ in the project
as i use a jpeg image for test the image wasn't uploaded until i changed the order of mimetypes this way:
new \Upload\Validation\Mimetype('image/jpeg', 'image/png'),

**Comment by Juju075** [comment]
Ok merci je regarde.

Le dim. 7 nov. 2021 à 01:13, itahriouan1 ***@***.***> a
écrit :

**Comment by Juju075** [comment]
Hello,
Php error for DIR
accept $storage = new \Upload\Storage\FileSystem( __DIR__."/../uploads/images/");
************************

**Comment by Juju075** [comment]
Ok thx Zakaria that works.

**Comment by Juju075** [comment]
Just last issue.
The name of the file has been changed logo.jpeg to 6187c4abf3f88.jpg

**Comment by Juju075** [comment]
ok works fine

**Comment by Juju075** [comment]
uploads must be in public file for production.

**Comment by Juju075** [comment]
Ok  nice :)
