### ISSUE TITLE
IMPORTANT LAST ONE - 90% Admin dashboard | getCommentToValidate() |Display all comments to be validate

### ISSUE THREAD

**Issue by Juju075** [Juju075/Openclassrooms#77]

**Comment by itahriouan1** [comment]
Hello Bempime, Multiple requests in getCommentToValidate() should be replaced by only one request joining 3 tables:

```
public function getCommentToValidate(){
        $cards = [];
        $this->getBdd();
        $cards=[];    
        $req = self::$_bdd->prepare('SELECT article.title, comment.content, user.nom, user.prenom FROM comment, user, article WHERE comment.id_article=article.id_article and user.id_user=comment.id_user and comment.disabled = 0');    
        $req->execute();
        $Comments = $req->fetchAll(\PDO::FETCH_ASSOC);
        $cards=$Comments;
        return $cards;
    }
```
in ControllerAdmin exactly in dashboard function there is no need to send card to the view using session peremeters you sould replace it by. you should send card in the array sent by displayForm method:
```

         $cards = $this->adminManager->getCommentToValidate();
         var_dump($cards);
         
         //$_SESSION['cards']=$cards;

         $this->_view = new View('singlePost','Admin');
         $this->_view->displayForm('Admin',array('cards'=>$cards,'countarticles'=>$countarticles,'countcomments1'=>$countcomments1,'countcomments0'=>$countcomments0,'countusers'=>$countusers));        
        
         //unset($_SESSION['cards']);

```
in view.php you should receive card variable and send it using twig render:

```
$cards = $data['cards'];
                
            echo $twig->render($page1 ['countarticles'=>$countarticles,'countcomments1'=>$countcomments1,'countcomments0'=>$countcomments0,'countusers'=>$countusers, 'cards'=>$cards,'usertype'=>$usertype]);
```
in view.Admin.html.twig you sould replace cards variable by card:
```

               <span class="h3">{{ card.title }}</span></a
              ><br />
              <span>{{ card.content }}</span
              ><br />
              <span>{{ card.prenom }} {{ card.nom }}</span
              ><br />
              <span>{{ card.createdat }}</span>
            </div> 

```
that's it.

good luck

**Comment by Juju075** [comment]
Ok repetition comes from cards.attribute instead of  card.attribute 👍 

SQL request its just another level 1 line target
Thanks 
*********************************************
Just blocked at viewAdmin.html.twig

Array to string conversion in C:\wamp64\www\App_Blog_MVC\vendor\twig\twig\src\Environment.php(358) : eval()'d code on line 178
*************************
Test Bdd multi comments to gets not just 1.

**Comment by Juju075** [comment]
and missing data from moderator link and erase for buttons  je valide and je refuse
I will try to add it in sql.

**Comment by Juju075** [comment]
ok ajout grâce aux jointure super mais...
la requête crée une boucle x1 x2 x3 selon le nombres de commentaires lister.

**Comment by itahriouan1** [comment]
I have modified the request by joining moderator table and it works fine. this is the request i have used:
`SELECT article.title, comment.content, user.nom, user.prenom, moderator.link, moderator.createdat, moderator.erase FROM comment, user, article, moderator WHERE comment.id_article=article.id_article and user.id_user=comment.id_user and comment.id_comment=moderator.id_comment and comment.disabled = 0`
is this the sql request that you have defined?

**Comment by Juju075** [comment]
yes

Le jeu. 11 nov. 2021 à 20:42, itahriouan1 ***@***.***> a
écrit :

**Comment by Juju075** [comment]
ok ca marche
Juste corriger le delete pour le bouton delete commentaire
admin&comment=delete&id=266
petite erreur  et c bon.

**Comment by Juju075** [comment]
ok
